name: e2e test

on:
  pull_request: 
    branches: ['main']
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - windows-2016
        - windows-2019
        - windows-2022

        include:
        - platform: ubuntu-latest
          want: '^$'
        - platform: windows-2016
          want: '^10\.0\.14393$'
        - platform: windows-2019
          want: '^10\.0\.17763$'
        - platform: windows-2022
          want: '^10\.0\.20348$'

    name: e2e ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - run: |
        go run ./cmd/
        go run ./cmd/ | grep ${{ matrix.want }}
